from svgpathtools import svg2paths
import os

def svg_to_grbl_gcode(input_svg_path, output_gcode_path, safe_z=5.0, cut_z=-1.0, feed_rate=800, travel_rate=1500, segments_per_curve=20):
    """
    Chuyển đổi file SVG thành G-code cho GRBL.
    :param safe_z: Độ cao an toàn khi di chuyển dao (mm)
    :param cut_z: Độ sâu khi cắt/khắc (mm)
    :param feed_rate: Tốc độ cắt (F trong G-code, mm/phút)
    :param travel_rate: Tốc độ di chuyển nhanh khi nhấc dao (mm/phút)
    :param segments_per_curve: Số đoạn thẳng dùng để băm nhỏ đường cong Bezier (càng cao càng mịn)
    """
    print(f"Đang đọc file SVG: {input_svg_path}...")
    if not os.path.exists(input_svg_path):
        raise FileNotFoundError(f"Không tìm thấy file: {input_svg_path}")

    # Đọc các đường dẫn (paths) từ file SVG
    paths, _ = svg2paths(input_svg_path)
    
    gcode = []
    
    # 1. Khởi tạo Header G-code chuẩn cho GRBL
    gcode.append("; --- CNC G-CODE GENERATED BY PYTHON ---")
    gcode.append("G21 ; Thiết lập đơn vị: Milimet (mm)")
    gcode.append("G90 ; Thiết lập tọa độ tuyệt đối")
    gcode.append("M3 S10000 ; Bật trục chính (Spindle) quay thuận, tốc độ 10000 RPM")
    gcode.append(f"G0 Z{safe_z:.2f} ; Nhấc dao lên độ cao an toàn")
    gcode.append(f"G0 F{travel_rate} ; Thiết lập tốc độ di chuyển nhanh")
    
    print("Đang biên dịch các đường vector thành tọa độ CNC...")
    
    # 2. Duyệt qua từng Path (Mỗi path đại diện cho một nét hoặc một lỗ đã gộp)
    for path in paths:
        if len(path) == 0:
            continue
            
        # Lấy điểm khởi đầu của đường path này
        start_point = path[0].start
        start_x = start_point.real
        # SVG có trục Y hướng xuống, máy CNC có trục Y hướng lên. Ta đảo dấu Y để hình không bị ngược.
        start_y = -start_point.imag 
        
        # Di chuyển nhanh dao đến vị trí bắt đầu trên mặt phẳng XY
        gcode.append(f"G0 X{start_x:.3f} Y{start_y:.3f}")
        # Lao dao xuống độ sâu cắt cut_z với tốc độ feed_rate
        gcode.append(f"G1 Z{cut_z:.3f} F{feed_rate}")
        
        # Duyệt qua từng phân đoạn (Segment) bên trong Path
        for segment in path:
            # Thuật toán băm nhỏ đường cong (Bezier/Arc) thành các chuỗi đoạn thẳng nhỏ G1
            # giúp máy GRBL không bị lỗi nội suy và đường cắt cực kỳ mịn.
            num_steps = segments_per_curve if hasattr(segment, 'control1') else 1
            
            for i in range(1, num_steps + 1):
                t = i / num_steps
                point = segment.point(t)
                x = point.real
                y = -point.imag
                gcode.append(f"G1 X{x:.3f} Y{y:.3f}")
                
        # Sau khi cắt xong 1 đường khép kín, nhấc dao lên độ cao an toàn trước khi qua đường khác
        gcode.append(f"G0 Z{safe_z:.2f}")
        gcode.append("") # Xuống dòng cho rõ ràng giữa các nét

    # 3. Kết thúc chương trình G-code (Footer)
    gcode.append("; --- KẾT THÚC CHƯƠNG TRÌNH ---")
    gcode.append(f"G0 Z{safe_z:.2f} ; Nhấc dao an toàn")
    gcode.append("G0 X0 Y0 ; Quay về tọa độ gốc Gốc 0")
    gcode.append("M5 ; Tắt trục chính Spindle")
    gcode.append("M30 ; Kết thúc chương trình hoàn toàn")

    # 4. Ghi dữ liệu ra file G-code
    with open(output_gcode_path, "w") as f:
        f.write("\n".join(gcode))
        
    print(f"Thành công! File G-code dành cho GRBL đã được lưu tại: {output_gcode_path}")

# --- CHẠY THỬ NGHIỆM ---
try:
    svg_to_grbl_gcode(
        input_svg_path="ket_qua_vector_co_lo.svg", 
        output_gcode_path="cnc_output.nc",
        safe_z=5.0,       # Nhấc dao cao cách mặt gỗ 5mm khi di chuyển
        cut_z=-1.5,       # Phay sâu xuống mặt gỗ 1.5mm (dấu âm)
        feed_rate=1000,    # Tốc độ ăn dao phay 1000 mm/phút
        travel_rate=2000   # Tốc độ chạy không tải 2000 mm/phút
    )
except Exception as e:
    print(f"Có lỗi xảy ra: {e}")