services:
  redis:
    image: redis:7-alpine
    container_name: tot-redis
    privileged: true
    command: redis-server --requirepass Test123456 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./db_test/redis:/data
    restart: always

  postgres:
    image: ankane/pgvector
    container_name: tot-postgres
    privileged: true
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Test123456
      POSTGRES_DB: tot_db
    ports:
      - "54321:5432"
    volumes:
      - ./db_test/postgres:/var/lib/postgresql/data
    restart: always

  mariadb:
    image: mariadb:10.11
    container_name: tot-mariadb
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: Test123456
      MYSQL_DATABASE: tot_db
    ports:
      - "3306:3306"
    volumes:
      - ./db_test/mariadb:/var/lib/mysql
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: tot-mongodb
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Test123456
    ports:
      - "27017:27017"
    volumes:
      - ./db_test/mongodb:/data/db
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tot-mssql
    privileged: true
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Test123456
    ports:
      - "1433:1433"
    volumes:
      - ./db_test/mssql:/var/opt/mssql
    restart: always

  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: tot-oracle
    privileged: true
    environment:
      ORACLE_PASSWORD: Test123456
    ports:
      - "1521:1521"
    volumes:
      - ./db_test/oracle:/opt/oracle/oradata
    restart: always
